version: '3'
services:
  api-heroes:
    build: . 
    ports: 
      - 3000:3000
    environment:
      MONGO_URL: mongodb

    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:4.2.5
    ports:
      - 27017:27017

      
